### ISSUE TITLE
setup.py Fails

### ISSUE THREAD

**Issue by ryanohoro** [scanner/asimap#1]
When running setup:

```
python2 setup.py install
  File "setup.py", line 21
    setup_requires=['pytest-runner',],
                 ^
SyntaxError: invalid syntax
```

Appears the preceding line is missing a comma. Adding this comma allows successful setup.

**Comment by scanner** [comment]
The python2 version does not work for installing via setup.. but the python3 version can successfully build a package wheel that can be installed.
